name: main

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      PYTHON_VERSION: 3.13
      POETRY_VERSION: 2.0.1

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_HOME="$HOME/.poetry" python - --yes
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'

      - name: Assert GitHub Release tag matches the library version
        run: |
          library_version=$(poetry version -s)

          if [ "$library_version" != "$GITHUB_RELEASE_TAG" ]; then
              echo "❌ Release tag ($GITHUB_RELEASE_TAG) does not match the library version in pyproject.toml ($library_version)."
              exit 1
          fi

          echo "✅ Release tag matches the library version in pyproject.toml: $library_version"
        env:
          GITHUB_RELEASE_TAG: ${{ github.event.release.tag_name }}

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Build package
        run: poetry build
