name: Release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download Python package dist artifacts from build
        uses: actions/download-artifact@v4
        with:
          name: distfiles
          path: dist/

      - name: Publish Python package dist artifacts to GitHub Release assets
        run: gh release upload "${GH_RELEASE_TAG}" dist/*.{tar.gz,whl}
        env:
          GH_TOKEN: ${{ github.token }}
          GH_RELEASE_TAG: ${{ github.event.release.tag_name }}

      - name: Publish package to PyPI
        run: |
          echo "Publishing package to PyPI..."

          # After verifying the release tag and running code linters, tests, and builds,
          # as a last step, we can publish the package to PyPI.

          # See https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
