name: Release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  release-to-github:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: build
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download Python package dist artifacts from build
        uses: actions/download-artifact@v4
        with:
          name: distfiles
          path: dist/

      - name: Publish Python package to GitHub Release assets
        run: gh release upload "${GH_RELEASE_TAG}" dist/*.{tar.gz,whl}
        env:
          GH_TOKEN: ${{ github.token }}
          GH_RELEASE_TAG: ${{ github.event.release.tag_name }}

  release-to-pypi:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: build

    steps:
      - name: Download Python package dist artifacts from build
        uses: actions/download-artifact@v4
        with:
          name: distfiles
          path: dist/

      - name: Install Twine
        run: pip install twine

      - name: Publish Python package to package index
        run: |
          echo "Publishing Python package to a package index..."

          # After verifying the release tag and running code linters, tests, and builds,
          # as a last step, we can publish the package to package index, e.g., PyPI.

          # See https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
